# This program can be used to ask user Name and Age, It will analyse the length of the name (in characters) and will show the age in a year.

print ("Hello, My name is Mr. Program!!!")
print ('')
print ("What's your name?")
print ('')
myName = input()
print ('')
print ('welcome "' + myName + '" !!! ' + 'Your name has "' + str (len(myName)) + '" character.')
print ('')
print ("What is your age?")
print ('')
myAge = input()
print ('')
print ('You will be "' + str(int(myAge) + 1) + '" in a year.')
